C:/Users/nickm/Documents/GitHub/ACES_ECU/ACES_ESB/ESB_funcs.h File Reference
Function prototypes, macros, constants, and global variables for ESB microcontroller.
#include <avr/sfr_defs.h>
#include <float.h>
Macros
#define bit_is_set(sfr, bit) (_SFR_BYTE(sfr) & _BV(bit))
Simple function define for testing if the bit is set.
#define bit_is_clear(sfr, bit) (!(_SFR_BYTE(sfr) & _BV(bit)))
Simple function define for testing if the bit is clear.
#define SSACTIVE assign_bit(&SPI_PORT, CJC_SS, 0)
#define SSPASSIVE assign_bit(&SPI_PORT, CJC_SS, 1)
#define K_factor 91387
#define density 0.81
#define pump_m 0.382587
#define pump_b 0.195783
#define max_time 0.25
#define pump_tot_V 9.9
#define gVolts 1.75
#define Kp -0.0006
#define Kd -0.0004
#define lube_factor 3
#define sMotor 5.0
#define errorAllow 0.2
#define max_len 50
#define allData 9
#define ECU_timer_val 3036
#define HallTime 2760
#define CJC_MSK 0x7
#define normalDataIn 11
#define MISO 3
#define MOSI 2
#define SCK 1
#define CJC_SS 0
#define glowPin 4
#define solePin 5
#define lubePin 6
#define startPin 7
#define pumpPin 4
#define SPI_PORT PORTB
Functions
void Initial (void)
Initializes the microcontroller for its mainline execution.
void assign_bit (volatile uint8_t *sfr, uint8_t bit, uint8_t val)
Sets the specified bit to the specified value or does nothing if it already set to that.
void shutdown (void)
Forces an engine shutdown and closes all output ports which could actuate the engine.
void startup (void)
Performs the function calls in order such that and engine startup would occur.
void throttle (void)
Sets the fuel flow rate such that the engine would operate at a desired throttle value.
void EGT_collect (void)
Collects the temperature from the Exhaust Gas Thermocouple and then packages/send data to the ECU.
uint8_t SPI_Receive (void)
Performs the operations needed to communicate with the CJC via SPI.
void getTemp (uint8_t *tempString)
Converts the bytes received from the CJC into a usable temperature.
void package_message (void)
Packages the message to later be sent to the ECU.
void compressor (void)
Sets the duty cycle for the starter motor such that the compressor safely reaches a desired RPM.
void fuel_puffs (void)
Operates the fuel pump and fuel/lubrication solenoids such that ignition begins in the combustion chamber.
void heatSoaking (void)
Prevents interruptions from the operation of the engine so that the temperature of the combustion can will increase.
void setPWM (void)
Sets all of the Initializations for the PWMs for the Fuel Pump, Solenoids, and Starter Motor.
void coolingMode (void)
Shuts off the engine with the exception of the starter motor to force cool air through the engine.
void sendToECU (uint8_t len)
Routine to send a number of bytes to the ECU over RS232.
void waitMS (uint16_t msec)
Waits for a designated number of milliseconds.
void ECUconnect (void)
uint8_t calculateParity (uint8_t message[], uint8_t start_index)
Calculates the parity bytes for a set of 6 bytes.
uint8_t countOnes (uint8_t byte)
uint8_t checkParity (void)
This function checks that the parity bytes sent by the ECU match what the ESB generates.
Variables
uint8_t connected
This will describe whether or not the ESB is connected to the ECU.
uint8_t opMode
Describes critical information about the current state of the engine.
uint8_t throttle_val
Value 1-100 for the the user wants to set the throttle to.
uint8_t hallDone
Flag which describes if the current hall effect sampling period has concluded.
uint8_t startUpLockOut
Flag which determines if an engine startup will currently be prevented.
uint16_t hallCount
The number of pulses recorded in the current sampling period.
uint8_t hasInterrupted
Flag which describes whether the current data transmission has been interrupted by an ISR.
uint8_t commandCode
Describes which type of information the ESB is receiving from the ECU, either normal data or a command.
uint8_t ECUreceiveCount
Counter to keep track of the current index in a message received from the ECU.
unsigned char glowPlug
Flag for if the glow plug is on or off.
float desMFlow
Value of the desired amount of fuel flow.
float V_per_pulse
Value for how much voltage applied to the fuel pump corresponds to a single pulse from the flow meter.
float pulse_flow
The amount of pulses expected per each g/sec of fuel flow.
float bat_voltage
Value of the current lipo battery voltage.
uint8_t ECUtransmit [14]
Array for the message to send to the ECU.
uint8_t ECUreceive [7]
Array for the message received from the ECU.
uint16_t hallEffect
Current RPM of recorded by the hall effect sensor.
float EGT
The current exhaust gas temperature.
float ref_temp
Ambient temperature recorded on the ESB. This is currently unimplemented.
xx xx xx xx xx xx xx xx xx
union {
 uint8_t c [4]
 float f
} massFlow
Current value of mass flow.
Detailed Description
Function prototypes, macros, constants, and global variables for ESB microcontroller.
Author
Nick Moore
Date
March 22, 2018
Bug
Bug No known bugs
Macro Definition Documentation
bit_is_set
#define bit_is_set(sfr, bit) (_SFR_BYTE(sfr) & _BV(bit))
Simple function define for testing if the bit is set.
Description of the opModes: OpMode 1: An engine shutdown has been requested OpMode 2: An engine startup is in progress OpMode 3: An engine throttle adjustment is needed OpMode 4: The flow meter is being waited on so that the throttle can be adjusted again OpMode 5: The engine is in the cooling mode OpMode 6: The engine is doing nothing OpMode 7: Special Shutdown, the EGT is not working properly and so there cannot be a normal cooling mode OpMode 8: Engine is operating at the desired throttle, within the designated error tolerance OpMode 9: Fuel is not flowing when it should be flowing OpMode 10: Engine has reached idle OpMode 11: Messages sent from the ECU have failed the parity check OpMode 12: Engine Temperature limit has been reached, shutting down OpMode 13: RPM limit has been reached, shutting down
Definition at line 35 of file ESB_funcs.h.
Function Documentation
assign_bit()
void assign_bit (volatile uint8_t * sfr, uint8_t bit, uint8_t val)
Sets the specified bit to the specified value or does nothing if it already set to that.
Parameters
out sfr Pointer to Special Function Register the bit is located in.
in bit Denotes the bit which would like to be changed.
in val The value, either 1 or 0, that the user would like the bit to be after the function call.
Returns
void
Definition at line 21 of file ESB_funcs.c.
{
    if (val) // This is for if I want the value to be a 1
    {
        val = (val << bit);
        *sfr |= val;
    }
    else // This is for if I want the value to be a 0
    {
        val = ~(1 << bit);
        *sfr &= val;
    }
}
calculateParity()
uint8_t calculateParity (uint8_t message[], uint8_t start_index)
Calculates the parity bytes for a set of 6 bytes.
Parameters
in message Array of bytes which contains all the data to be sent to the ECU
in start_index Starting index for the six bytes by which to calculate the parity byte
Returns
uint8_t
Definition at line 176 of file Communication.c.
References countOnes().
{
    // This will return the parity byte for a message made up of 6 sequential bytes, starting with
       start_index
    uint8_t parity = 0;
    
    // first need to get the number of high bits in the first three bytes in the set
    for (unsigned set = 0; set < 2; set++){
        unsigned char count = 0;
        for (unsigned char i = 0; i < 3; i++){
            count += countOnes(message[start_index + set*3 + i]);
        }
        // now that I have the count for this set, I need to take the modulo
        count = count % 16; // Modulo with 16 because I have 4 bits to play with
        
        // now add this into the parity byte
        parity |= count << (4 * set); // this will make it so that bytes 0-2 will take up the LSB of the
       parity byte
    }
    // now copy this byte into memory
    return parity;
}
checkParity()
uint8_t checkParity (void)
This function checks that the parity bytes sent by the ECU match what the ESB generates.
Parameters
in void
Returns
unsigned char
Definition at line 220 of file Communication.c.
References calculateParity(), and ECUreceive.
{
    uint8_t result = 0;
    uint8_t parity1 = calculateParity(ECUreceive, 0);
    uint8_t parity2 = calculateParity(ECUreceive, 3);
    
    if (parity1 == ECUreceive[9] && parity2 == ECUreceive[10]){
        result = 1;
    }
    return result;
}
compressor()
void compressor (void)
Sets the duty cycle for the starter motor such that the compressor safely reaches a desired RPM.
1) This function uses a proportional-derivative control law to quickly get to the desired RPM of 10,000 RPM The reason this RPM was chosen is because it was listed in one of the data sheets for the JetCat engine
2) This control law uses gain which have been estimated based on the desired rise time and such. However, these gains have not been tested at all and should not be trusted.
3) If would be recommend that instead of using a fixed value for the voltage that can be supplied to the motor (see pump_tot_V)
Parameters
void
Returns
void
Definition at line 163 of file Engine_funcs.c.
{
    // For this function, the PD control law needs to be implemented
    //so that the engine gets to 10,000 RPM as quickly as possible
    char slope = 0; // this will be a linear slope for the current rate of change of RPM
    
    // first turn on the glow plug
    OCR2A = 255 - ((uint8_t) (gVolts / pump_tot_V * 255.0));
    // now turn on the prescalar
    TCCR2B |= (1 << CS22) | (1 << CS20); // this is a prescalar of 1024
    glowPlug = 1; // so that the PC can also record that the glow plug is on
    
    // now turn on the starter motor
    OCR0A = 255 - ((uint8_t) (sMotor / pump_tot_V * 255.0));
    TCCR0B |= (1 << CS02) | (1 << CS00);
    
    while (!(hallEffect < 10500 && hallEffect > 9500 && slope < 10 && slope > -10))
    {
        // now need to find new voltage
        float voltage = Kp*(hallEffect - 10000) + Kd*slope;
        if (voltage > 6.0) // Cap the voltage at the maximum the motor is rated for
            voltage = 6.0;
        else if (voltage < 0.0)
            voltage = 0.0; // some error checking to make sure that things to not get unbounded
        // now convert this into a duty cycle
        float duty = voltage / pump_tot_V;
        
        // now change the duty cycle on the starter motor
        OCR0A = 255 - ((uint8_t) (duty * 255.5));
        hallDone = 0;
        uint16_t hallPrev = hallEffect;
        // now wait for the next hall effect sensor measurement
        while (!hallDone);
        
        if (opMode == 1){ // This means that a shutdown has been invoked
            return;
        }
        
        // now calculate the new slope
        slope = (hallPrev - hallEffect) / 0.25;
        
    }
    
}
coolingMode()
void coolingMode (void)
Shuts off the engine with the exception of the starter motor to force cool air through the engine.
Parameters
void
Returns
void
Definition at line 308 of file Engine_funcs.c.
References EGT.
{
    // for this I will make sure that the starter motor receives 4V
    // This will force cool air through the engine
    
    if (EGT > 100){
        // first need to make sure that the PWM is working
        TCCR0A |= (1 << WGM01) | (1 << WGM00) | (1 << COM0A0) | (1 << COM0A1);
        TCCR0B |= (1 << WGM02);
        OCR0A = (uint8_t) (255 - sMotor * 255.0 / pump_tot_V); // When combine with a prescalar
       of 1024, this will have a period of 0.016384 seconds
    
        // Now start with the proper duty cycle
        TCCR0B |= (1 << CS00) | (1 << CS02);
    }
    else{ // this means that the engine has cooled sufficiently
        TCCR0A = 0;
        TCCR0B = 0;
        assign_bit(&PORTB, startPin, 0); // make sure the starter motor is turned off
        opMode = 6; // this means that the engine is just kind of chilling
    }
    
    
}
EGT_collect()
void EGT_collect (void)
Collects the temperature from the Exhaust Gas Thermocouple and then packages/send data to the ECU.
Parameters
in void
Returns
void
Definition at line 40 of file ESB_funcs.c.
{
    // Now loop through 4 bytes for the receive message
    uint8_t tempString[2];
    SSACTIVE; // drop the SS line for the CJC
    for (int i = 0; i < 2; i++){
        tempString[i] = SPI_Receive();
    }
    SSPASSIVE; // raise the SS line again since we are done
    
    // Now interpret this data string into an actual temperature
    getTemp(tempString);
            
    // Now package the message
    package_message();
}
fuel_puffs()
void fuel_puffs (void)
Operates the fuel pump and fuel/lubrication solenoids such that ignition begins in the combustion chamber.
1) This function starts by first applying voltage so that there will be some fuel pressure on the back of the closed fuel and lubrication solenoids.
2) Then the solenoid will begin opening with a duty cycle of 5% and increase by 5% every iteration in the loop. Each iteration of the loop will occupy 0.25 secs of time.
 3) The Lubrication solenoid will then be toggled at an interval as specified by lube_factor (see header file). This value corresponds to the factor by which the lubrication solenoid is slower than the fuel solenoid.
4) Once the exhaust gas temperature gets above 200C, then the starter motor and glow plug will turn off as it can be assumed that the ignition has been seeded.
Parameters
void
Returns
void
Definition at line 225 of file Engine_funcs.c.
{
    // If the code has made it this far then the compressor is up to speed
    // first I need to apply 2 volts of pressure with the fuel pump
    OCR3B = ICR3 - (unsigned int)(ICR3 * 2.0 / pump_tot_V); // This will set the duty cycle so
       that there is 2 volts received by the pump
    
    // now change the prescalar so the pump will turn on, prescalar of 8
    TCCR3B |= (1 << CS31);
    
    // Now begin with increasing the duty cycle
    float duty = 0.0;
    OCR1B = ICR1 - (unsigned int)(ICR1 * duty);
    // now turn on the fuel solenoid with a prescalar of 256
    TCCR4B |= (1 << CS42);
    
    // NOTE: It would be beneficial to have the output line for the fuel solenoid tied to a PCINT pin (such
       as PB6) and then
    // toggle the lubrication solenoid through the use of an interrupt. Becuase of this the actuation of
       the lubrication
    // solenoid will be left unimplemented.
    
    while (duty != 1)
    {
        // now wait for the new value of Hall effect and EGT, wait for 2 cycles so that 0.5 seconds will
       elapse
        hallDone = 0;
        while (!hallDone);
        hallDone = 0;
        while (!hallDone);
        
        if (opMode == 1) // This means that a shutdown has been invoked
            return;
            
        if (EGT > 200) { // if true, turn off the starter motor and glow plug. Do your own check to
       make sure that 200C is a good temp to turn this off at
            TCCR2A = 0; // this will return the pin to its normal state
            TCCR2B &= 0xF8; // this will turn off the glow plug
            assign_bit(&PORTB, glowPin, 0); // force the pin low
            TCCR0A = 0;
            TCCR0B &= 0xF8; // this will turn off the starter motor
            assign_bit(&PORTB, startPin, 0); // for the pin low
        }
        duty += 0.05;
        OCR4B = ICR4 - (unsigned int)(ICR4 * duty);
    }
    if (!massFlow.f)
        opMode = 9; // This is the opMode for if the fuel is not flowing
    
}
getTemp()
void getTemp (uint8_t * tempString)
Converts the bytes received from the CJC into a usable temperature.
Parameters
in tempString Array of chars which contains all the data received by the CJC
Returns
void
Definition at line 84 of file ESB_funcs.c.
References EGT, and ref_temp.
{
    // First check to see if there is a fault
    if (tempString[1] & 0x04)
        EGT = 0; // This means that the Thermocouple is open, check connection
    else { // If it makes it to here then there are no faults
        int val = (tempString[0] << 5) | (tempString[1] >> 3);
        if (!val)
            val = 1; // set the value to this for anything that is less than 3
        EGT = ((float) val / 4095.0) * 1023.75; // Since the temperature is on the scale of
       0->1023.75 and it has 12 bit resolution
        ref_temp = 0; // This is unimplemented at this time as the
       MAX6675 does not transmit the reference temperature
        
    }
}
heatSoaking()
void heatSoaking (void)
Prevents interruptions from the operation of the engine so that the temperature of the combustion can will increase.
1) This function is pretty simple, it sets a timer for 15 seconds and hogs execution until the timer has completed. During this time, the throttle is not allowed to be changed.
2) If this step is completed then it can be said that the engine has reached idle*
Parameters
void
Returns
void
Definition at line 282 of file Engine_funcs.c.
References assign_bit(), bit_is_clear, and opMode.
{
    // during this time the starter motor will not be using its PWM, timer0 (8 bit)
    TCCR0A = 0; // make this work as a normal timer
    TCCR0B = 0; // reset everything to 0
    
    // Now figure out the prescalars
    TCNT0 = 100;
    assign_bit(&TIMSK0, TOIE0, 0); // make sure there are not any overflow interrupts
    TCCR0B |= (1 << CS02) | (1 << CS00); // have a prescalar of 1024 and starts the timer
    
    for (uint16_t i = 0; i < 1500; i++){
        while (bit_is_clear(TIFR0,TOV0));
        assign_bit(&TIFR0, TOV0, 1); // clear by writing a 1 to it
        TCNT0 = 100; // This will have the timer run for 0.1 seconds
    }
    // If it has made it to here then the engine has reached idle
    opMode = 10;
}
Initial()
void Initial (void)
Initializes the microcontroller for its mainline execution.
This performs the following functions:
1) Initializes the PORT data directions. 0 for input and 1 for output
2) Initializes the ADC for use by EGT
3) Initializes the External Interrupt line for use by the Hall effect Sensor
4) Initializes the I2C communication with the on board temperature sensors
5) Initializes the SPI communication with the ECU
6) Enable a timer for use by the Hall effect sensor
7) Enable a timer to determine if ignition is taking too long
8) Enable global interrupts
Parameters
void
Returns
void
Definition at line 37 of file Initial_funcs.c.
{
    // Now do port directions for the PWM outputs
    DDRB |= (1 << PB4) | (1 << PB5) | (1 << PB7); // This sets the output for the pump, starter motor,
       and solenoids
    DDRE |= (1 << PE4);
    
    
    // The next things that need to be set are as follows
    // 1) Set Enable the correct port directions
    // 2) Enable SPI, Master operation, and the clock rate
    
    DDRB = (1 << MOSI) | (1 << SCK) | (1 << CJC_SS) | (0 << MISO);
    SPCR = (1 << SPE) | (1 << MSTR) | (1 << SPR0); // This will enable SPI mode 0 with a clock rate of
       Fosc/16
    
    // The CJC will be sampled at the end of the Hall Effect Sampling period
    
    // This will be used with the Hall effect sensor
    assign_bit(&DDRD, INT2, 0); // Configure the PD2 pin as an input so that it can
       receive the signals
    hallCount = 0;
    EICRA = (1 << ISC20) | (1 << ISC21); // This will enable rising edge interrupts on INT2, see page
       110 in datasheet
    
    UBRR0 = 12; // With a 16 MHz clock this will make a baud rate of 76800 (error of 0.16%)
    // The next things that need to be set are as follows (reference page 220 in datasheet)
    // 1) Enable receive interrupts
    // 2) Enable receiver
    // 3) Enable transmitter
    UCSR0B = (1 << RXCIE0) | (1 << RXEN0) | (1 << TXEN0);
    // Now set the framing information
    // I want the following things
    // 1) Asynchronous USART
    // 2) No Parity
    // 3) 1 Stop bit
    // 4) 8 bit character size
    UCSR0C = (1 << UCSZ01) | (1 << UCSZ00); // Now the USART should be ready to receive
            
    
    // Now initialize the timer for both the ECU communication error checking
    TCNT5 = ECU_timer_val;
    TIMSK5 = (1 << TOIE5); // enable overflow interrupts on this mode of timer 5
        
    // This will be set to 0.25 seconds so there is a reasonable sampling period
    TCNT4 = HallTime;
    TIMSK4 = (1 << TOIE4); // enable overflow interrupts for the Hall effect sensor timer
    waitMS(195); // wait this portion of time so that the ECU comm and Hall
       effect interrupts are off phase
    TCCR4B = (1 << CS41) | (1 << CS40); // start timer 4 with prescalar of 64
    pulse_flow = (1.0 / density) * K_factor * max_time / 1000; // this is the pulses expected
       per g/s in 0.25 sec
    V_per_pulse = pump_m / pulse_flow;
    
    sei();
    
    hasInterrupted = 0;
    commandCode = 0; // This means that that the next received char is a new command
    ECUreceiveCount = 0;
    
}
package_message()
void package_message (void)
Packages the message to later be sent to the ECU.
This function loads the message into the array and then calculates the corresponding parity bytes to append to the end of the array.
Parameters
void
Returns
void
Definition at line 36 of file Communication.c.
References calculateParity(), ECUtransmit, EGT, glowPlug, hallDone, hallEffect, opMode, and ref_temp.
{
    hallEffect = 34567;
    EGT = 12345;
    glowPlug = 1;
    ref_temp = 23456;
    
    ECUtransmit[0] = opMode;
    memcpy(ECUtransmit + 1, &hallEffect, sizeof(uint16_t));
    memcpy(ECUtransmit + 3, &EGT, sizeof(float));
    memcpy(ECUtransmit + 7, &glowPlug, sizeof(uint8_t));
    memcpy(ECUtransmit + 8, &ref_temp, sizeof(float));
    ECUtransmit[12] = calculateParity(ECUtransmit, 0);
    ECUtransmit[13] = calculateParity(ECUtransmit, 6);
    
    hallDone = 0; // reset this we have already used the new data
}
sendToECU()
void sendToECU (uint8_t len)
Routine to send a number of bytes to the ECU over RS232.
Parameters
in len The number of bytes from ECUtransmit to send to the ECU
Returns
void
Definition at line 157 of file Communication.c.
References ECUtransmit.
{
    // this will send the number of character in ESBmessage up to len
    cli();
    for(uint8_t i = 0; i < len; i++)
    {
        while (!(UCSR0A & (1<<UDRE0)));
        /* Put data into buffer, sends the data */
        UDR0 = ECUtransmit[i];
    }
    sei();
}
setPWM()
void setPWM (void)
Sets all of the Initializations for the PWMs for the Fuel Pump, Solenoids, and Starter Motor.
Parameters
in void
Returns
void
Definition at line 136 of file ESB_funcs.c.
{
    // First the Fuel pump will be a PWM on Timer 3
    TCCR3A |= (1 << WGM31); // set this for mode 14 waveform
    TCCR3B |= (1 << WGM32) | (1 << WGM33); // this sets the other 2 bits for the waveform generation
    TCCR3A |= (1 << COM3B1) | (1 << COM3B0); // This sets the other two bits for the waveform
       generation
    ICR3 = 40000; // With a prescalar of 8, this will have a period of 20
       ms
    
    // Now the fuel solenoid will be a PWM on Timer 1
    TCCR1A |= (1 << WGM11);
    TCCR1B |= (1 << WGM12) | (1 << WGM13);
    TCCR1A |= (1 << COM1B1) | (1 << COM1B0); // This is the same as for the fuel pump
    ICR1 = 31250; // With a prescalar of 256, this will have a period of
       0.5 sec
    
    // Now set up the Starter motor on Timer 0 (this an 8 bit timer instead of 16)
    TCCR0A |= (1 << WGM01) | (1 << WGM00) | (1 << COM0A0) | (1 << COM0A1); // This will set it to the
       Fast PWM
    TCCR0B |= (1 << WGM02);
    OCR0A = (uint8_t) (255 - sMotor * 255.0 / pump_tot_V); // When combine with a prescalar of
       1024, this will have a period of 0.016384 seconds
    
    // Now set up the Glow plug on Timer 2 (this is an 8 bit timer instead of 16)
    TCCR2A |= (1 << WGM21) | (1 << WGM20) | (1 << COM2A0) | (1 << COM2A1); // This is the same as for
       starter motor code
    TCCR2B |= (1 << WGM22);
    OCR2A = (uint8_t) (255 - gVolts * 255.0 / pump_tot_V);
    
}
shutdown()
void shutdown (void)
Forces an engine shutdown and closes all output ports which could actuate the engine.
This function performs the following functions: 1) Zeros out the prescalars for the operation of the following pieces of hardware: a) The starter motor b) The fuel solenoid b) The glow plug c) The fuel pump d) The lubrication solenoid
2) Zeros out the control registers for the same components. This has the effect of restoring the pin to its normal operation (see page 155 in datasheet)
Parameters
void
Returns
void
Definition at line 29 of file Engine_funcs.c.
References assign_bit().
{
    // For this just need to turn off the pump, glow plug, starter motor, and solenoids
    // Start with the starter motor
    TCCR0B = 0; // this will force the prescalar values to be zero
    TCCR0A = 0; // This will force normal operation of the pin (so that it can always be pulled low)
    assign_bit(&PORTB, startPin, 0);
    
    // Now the glow plug
    TCCR2B = 0;
    TCCR2A = 0;
    assign_bit(&PORTB, glowPin, 0);
    
    // now the pump
    TCCR3B = 0;
    TCCR3A = 0; // make sure the PWM loses authority
    assign_bit(&PORTB, pumpPin, 0);
    
    // now the fuel solenoid
    TCCR5B = 0;
    TCCR5A = 0;
    assign_bit(&PORTB, solePin, 0);
    
    // now the lube solenoid
    assign_bit(&PORTB, lubePin, 0);
    
    startUpLockOut = 1;
    opMode = 4; // An opMode of 4 means that the engine will enter the cooling mode
}
SPI_Receive()
uint8_t SPI_Receive (void)
Performs the operations needed to communicate with the CJC via SPI.
Parameters
in void
Returns
uint8_t
Definition at line 63 of file ESB_funcs.c.
{
    cli();
    /* Put data into buffer and start the transmission */
    SPDR = 0; // Since the CJC doesn't receive, we can put anything we want into the buffer
    
    /* Wait for data to be received */
    while (!(SPSR & (1<<SPIF)));
    
    /* Enable interrupts again */
    sei();
    
    /* Get and return received data from buffer */
    return SPDR;
}
startup()
void startup (void)
Performs the function calls in order such that and engine startup would occur.
1) This function checks to make sure that there is not a lockout which prevents the engine from starting. These engine lockouts are put in place such that the engine cannot be started until it has fully stopped. This is to prevent a startup in an unsafe situation.
2) If a lockout is not present then the next set is set the various PWM lines such that the designates I/O pins can drive the hardware vital to the engine.
3) The function invokes the compressor function which will begin spinning up the starter motor until it reaches the point at which the air is sufficiently compressed for combustion to occur. Meanwhile, the glow plug is turned on so that it can begin heating up.
4) The function begins injecting small puffs of fuel into the combustion chamber so that combustion will begin taking place and become self-sufficient.
5) Assuming there are no issues with the engine operation so far, a heat soaking procedure will then take place. This is essentially a process where the engine is just allowed to run without being interfered with so that the combustion chamber can reach a more optimal temperature.
Parameters
void
Returns
void
Definition at line 82 of file Engine_funcs.c.
References compressor(), EGT, fuel_puffs(), hallEffect, heatSoaking(), opMode, setPWM(), shutdown(), startup(), and startUpLockOut.
{
    if (startUpLockOut){
        if (hallEffect < 10 && EGT < 50){
            startUpLockOut = 0;
            startup(); // restart the function so that it has the opportunity to
       restart
        }
    }
    else{
        setPWM();
        compressor();
        if (opMode == 1)
            return;
            
        fuel_puffs();
        if (opMode == 1)
            return;
            
        if (hallEffect < 35000){ // This means that start up was not achieved
            shutdown(); // 35,000 RPM is the minimum required for startup
        }
        else{
            heatSoaking();
        }
    }
}
throttle()
void throttle (void)
Sets the fuel flow rate such that the engine would operate at a desired throttle value.
1) This function converts the desired throttle value into a mass flow rate. THIS MASS FLOW RATE IS DETERMINED ONLY FOR THE P90-RXI!
2) This mass flow rate is then converted into a number of flow rate pulses bases on the known linear relationship. See the published document for more explanation on this relationship.
3) The error, in terms of pulses, is then determined between the actual and desired flow rate of fuel.
4) The error is then converted into volts, which then can be used to directly translated into how many counts by which the input capture control register. This directly correlates to the duty cycle for the PWM signal which powers the fuel pump.
Parameters
void
Returns
Void
Definition at line 126 of file Engine_funcs.c.
References desMFlow, massFlow, pulse_flow, and throttle_val.
{
    // first I need to figure out what mass flow rate is desired for the requested throttle
    desMFlow = 4.8*((float) throttle_val / 255.0);
    uint8_t desPulses = (uint8_t) desMFlow*pulse_flow;
    
    // Now I need to increase the duty cycle depending in the difference from the expected flow rate
    uint8_t pulse_error = desPulses - (uint8_t) pulse_flow * massFlow.f;
    
    float difference = massFlow.f - desMFlow;
    if (difference < 0)
        difference = -difference;
    
    if (difference < errorAllow){
        opMode = 8; // this means that the desired throttle has been
       reached
    }
    
    float change = (float) pulse_error * V_per_pulse * ((float) ICR3 / pump_tot_V);
    OCR3B -= (uint16_t) change;
    if (opMode != 8)
        opMode = 4; // change the opMode so that it doesn't go through this again
       until there is a new flow measurement
}
waitMS()
void waitMS (uint16_t msec)
Waits for a designated number of milliseconds.
Parameters
in msec Value of milliseconds that are wanting to be waited for
Returns
void
Waits for a designated number of milliseconds.
Parameters
in msec Number of milliseconds that are desired to be delayed for
Returns
void
Definition at line 166 of file ESB_funcs.c.
{
    // This function utilizes timer 0 and a sequence of delay loops to delay for the desired time
    TCNT0 = 5;
    // begin the timer
    TCCR0B |= (1 << CS01) | (1 << CS00); // this will start the timer with a prescalar of 64
    for (uint16_t i = 0; i < msec; i++){
        while(bit_is_clear(TIFR0, TOV0));
        TIFR0 |= (1 << TOV0); // Clear the overflow flag by writing a 1 to it
    }
    assign_bit(&TCCR0B, CS01, 0);
    assign_bit(&TCCR0B, CS00, 0); // Turn off the timer
}