C:/Users/nickm/Documents/GitHub/ACES_ECU/ACES_ESB/Ethernet.h File Reference
Control register definitions and function prototypes for the ENC28J60 Ethernet controller.
#include <avr/sfr_defs.h>
#include `ESB_funcs.h`
Macros
#define ADDR_MSK 0x1F
#define CSACTIVE assign_bit(&SPI_PORT, Ethernet_SS, 0)
#define CSPASSIVE assign_bit(&SPI_PORT, Ethernet_SS, 1)
#define waitSPI() while(!(SPSR & (1<<SPIF)))
#define LED_on 0x0880
#define LED_off 0x0990
#define LED_normal 0x0476
#define half_sec_wait 34285
#define DEST_MAC 0
#define SRC_MAC 6
#define LEN_INDEX 12
#define READ_CONTROL_REG 0x00
#define READ_BUF_MEM 0x3A
#define WRITE_CONTROL_REG 0x40
#define WRITE_BUF_MEM 0x7A
#define BIT_FIELD_SET 0x80
#define BIT_FIELD_CLR 0xA0
#define SOFT_RESET 0xFF
#define ADDR_MASK 0x1F
#define BANK_MASK 0x60
#define SPRD_MASK 0x80
#define EIE 0x1B
#define EIR 0x1C
#define ESTAT 0x1D
#define ECON2 0x1E
#define ECON1 0x1F
#define ERDPTL (0x00|0x00)
#define ERDPTH (0x01|0x00)
#define EWRPTL (0x02|0x00)
#define EWRPTH (0x03|0x00)
#define ETXSTL (0x04|0x00)
#define ETXSTH (0x05|0x00)
#define ETXNDL (0x06|0x00)
#define ETXNDH (0x07|0x00)
#define ERXSTL (0x08|0x00)
#define ERXSTH (0x09|0x00)
#define ERXNDL (0x0A|0x00)
#define ERXNDH (0x0B|0x00)
#define ERXRDPTL (0x0C|0x00)
#define ERXRDPTH (0x0D|0x00)
#define ERXWRPTL (0x0E|0x00)
#define ERXWRPTH (0x0F|0x00)
#define EDMASTL (0x10|0x00)
#define EDMASTH (0x11|0x00)
#define EDMANDL (0x12|0x00)
#define EDMANDH (0x13|0x00)
#define EDMADSTL (0x14|0x00)
#define EDMADSTH (0x15|0x00)
#define EDMACSL (0x16|0x00)
#define EDMACSH (0x17|0x00)
#define EHT0 (0x00|0x20)
#define EHT1 (0x01|0x20)
#define EHT2 (0x02|0x20)
#define EHT3 (0x03|0x20)
#define EHT4 (0x04|0x20)
#define EHT5 (0x05|0x20)
#define EHT6 (0x06|0x20)
#define EHT7 (0x07|0x20)
#define EPMM0 (0x08|0x20)
#define EPMM1 (0x09|0x20)
#define EPMM2 (0x0A|0x20)
#define EPMM3 (0x0B|0x20)
#define EPMM4 (0x0C|0x20)
#define EPMM5 (0x0D|0x20)
#define EPMM6 (0x0E|0x20)
#define EPMM7 (0x0F|0x20)
#define EPMCSL (0x10|0x20)
#define EPMCSH (0x11|0x20)
#define EPMOL (0x14|0x20)
#define EPMOH (0x15|0x20)
#define EWOLIE (0x16|0x20)
#define EWOLIR (0x17|0x20)
#define ERXFCON (0x18|0x20)
#define EPKTCNT (0x19|0x20)
#define MACON1 (0x00|0x40|0x80)
#define MACON2 (0x01|0x40|0x80)
#define MACON3 (0x02|0x40|0x80)
#define MACON4 (0x03|0x40|0x80)
#define MABBIPG (0x04|0x40|0x80)
#define MAIPGL (0x06|0x40|0x80)
#define MAIPGH (0x07|0x40|0x80)
#define MACLCON1 (0x08|0x40|0x80)
#define MACLCON2 (0x09|0x40|0x80)
#define MAMXFLL (0x0A|0x40|0x80)
#define MAMXFLH (0x0B|0x40|0x80)
#define MAPHSUP (0x0D|0x40|0x80)
#define MICON (0x11|0x40|0x80)
#define MICMD (0x12|0x40|0x80)
#define MIREGADR (0x14|0x40|0x80)
#define MIWRL (0x16|0x40|0x80)
#define MIWRH (0x17|0x40|0x80)
#define MIRDL (0x18|0x40|0x80)
#define MIRDH (0x19|0x40|0x80)
#define MAADR1 (0x00|0x60|0x80)
#define MAADR0 (0x01|0x60|0x80)
#define MAADR3 (0x02|0x60|0x80)
#define MAADR2 (0x03|0x60|0x80)
#define MAADR5 (0x04|0x60|0x80)
#define MAADR4 (0x05|0x60|0x80)
#define EBSTSD (0x06|0x60)
#define EBSTCON (0x07|0x60)
#define EBSTCSL (0x08|0x60)
#define EBSTCSH (0x09|0x60)
#define MISTAT (0x0A|0x60|0x80)
#define EREVID (0x12|0x60)
#define ECOCON (0x15|0x60)
#define EFLOCON (0x17|0x60)
#define EPAUSL (0x18|0x60)
#define EPAUSH (0x19|0x60)
#define PHCON1 0x00
#define PHSTAT1 0x01
#define PHHID1 0x02
#define PHHID2 0x03
#define PHCON2 0x10
#define PHSTAT2 0x11
#define PHIE 0x12
#define PHIR 0x13
#define PHLCON 0x14
#define ERXFCON_UCEN 0x80
#define ERXFCON_ANDOR 0x40
#define ERXFCON_CRCEN 0x20
#define ERXFCON_PMEN 0x10
#define ERXFCON_MPEN 0x08
#define ERXFCON_HTEN 0x04
#define ERXFCON_MCEN 0x02
#define ERXFCON_BCEN 0x01
#define EIE_INTIE 0x80
#define EIE_PKTIE 0x40
#define EIE_DMAIE 0x20
#define EIE_LINKIE 0x10
#define EIE_TXIE 0x08
#define EIE_WOLIE 0x04
#define EIE_TXERIE 0x02
#define EIE_RXERIE 0x01
#define EIR_PKTIF 0x40
#define EIR_DMAIF 0x20
#define EIR_LINKIF 0x10
#define EIR_TXIF 0x08
#define EIR_WOLIF 0x04
#define EIR_TXERIF 0x02
#define EIR_RXERIF 0x01
#define ESTAT_INT 0x80
#define ESTAT_LATECOL 0x10
#define ESTAT_RXBUSY 0x04
#define ESTAT_TXABRT 0x02
#define ESTAT_CLKRDY 0x01
#define ECON2_AUTOINC 0x80
#define ECON2_PKTDEC 0x40
#define ECON2_PWRSV 0x20
#define ECON2_VRPS 0x08
#define ECON1_TXRST 0x80
#define ECON1_RXRST 0x40
#define ECON1_DMAST 0x20
#define ECON1_CSUMEN 0x10
#define ECON1_TXRTS 0x08
#define ECON1_RXEN 0x04
#define ECON1_BSEL1 0x02
#define ECON1_BSEL0 0x01
#define MACON1_LOOPBK 0x10
#define MACON1_TXPAUS 0x08
#define MACON1_RXPAUS 0x04
#define MACON1_PASSALL 0x02
#define MACON1_MARXEN 0x01
#define MACON2_MARST 0x80
#define MACON2_RNDRST 0x40
#define MACON2_MARXRST 0x08
#define MACON2_RFUNRST 0x04
#define MACON2_MATXRST 0x02
#define MACON2_TFUNRST 0x01
#define MACON3_PADCFG2 0x80
#define MACON3_PADCFG1 0x40
#define MACON3_PADCFG0 0x20
#define MACON3_TXCRCEN 0x10
#define MACON3_PHDRLEN 0x08
#define MACON3_HFRMLEN 0x04
#define MACON3_FRMLNEN 0x02
#define MACON3_FULDPX 0x01
#define MICMD_MIISCAN 0x02
#define MICMD_MIIRD 0x01
#define MISTAT_NVALID 0x04
#define MISTAT_SCAN 0x02
#define MISTAT_BUSY 0x01
#define PHCON1_PRST 0x8000
#define PHCON1_PLOOPBK 0x4000
#define PHCON1_PPWRSV 0x0800
#define PHCON1_PDPXMD 0x0100
#define PHSTAT1_PFDPX 0x1000
#define PHSTAT1_PHDPX 0x0800
#define PHSTAT1_LLSTAT 0x0004
#define PHSTAT1_JBSTAT 0x0002
#define PHCON2_FRCLINK 0x4000
#define PHCON2_TXDIS 0x2000
#define PHCON2_JABBER 0x0400
#define PHCON2_HDLDIS 0x0100
#define PKTCTRL_PHUGEEN 0x08
#define PKTCTRL_PPADEN 0x04
#define PKTCTRL_PCRCEN 0x02
#define PKTCTRL_POVERRIDE 0x01
#define RXSTART_INIT 0x0
#define RXSTOP_INIT (0x1FFF-0x0600-1)
#define TXSTART_INIT (0x1FFF-0x0600)
#define TXSTOP_INIT 0x1FFF
#define MAX_FRAMELEN 1500
Functions
uint8_t readBasic (uint8_t op, uint8_t address)
Performs a low level read operation of a register.
void writeBasic (uint8_t op, uint8_t address, uint8_t data)
Performs a low level write operation of a register.
void readBuffer (uint8_t len, uint8_t *data)
Reads a specified number of bytes from the buffer and stores them in an array.
void writeBuffer (uint8_t len, uint8_t *data)
Writes a specified number of bytes into the buffer memory.
void setBank (uint8_t address)
Set the current bank to that which corresponds to that of a specified register for the ENC28J60.
uint8_t RegisterRead (uint8_t address)
Reads the value for a specified register in memory for the ENC28J60.
void RegisterWrite (uint8_t address, uint8_t data)
Writes a byte of data to a specified register location for the ENC28J60.
uint16_t PhyRead (uint8_t address)
Reads from a register location from the PHY module within the ENC28J60.
void PhyWrite (uint8_t address, uint16_t data)
Writes to a register location in the PHY module within the ENC28J60.
void InitPhy (void)
Initialization routine for using the PHY module of the ENC18J60, mostly sets LED blink patterns.
void InitEthernet (void)
Initialization routine for use of the ENC28J60 in this project.
void waitMS (uint16_t msec)
Waits for a designated number of milliseconds.
void packetSend (uint8_t len, uint8_t *packet)
Sends a packet of information using the Ethernet module.
uint16_t packetRecieve (uint8_t max_length, uint8_t *packets)
Receives packet of information which is waiting in the buffer.
void transmitHeader (uint8_t *buffer)
Place the proper header bytes to the beginning of the array which will hold the message.
uint8_t loadData (uint8_t *fullMessage, uint8_t *message, uint8_t len)
Places data from temporary string into the final array which will be sent to the ENC28J60.
void readTX_StatusVec (uint8_t *Status)
Reads the transmit status vector from the address which is the end of the transmit buffer + 1.
Variables
uint8_t bankNumber
uint16_t nextPacketPtr
uint8_t trash
Detailed Description
Control register definitions and function prototypes for the ENC28J60 Ethernet controller.
Author
Nick Moore
Date
June 21, 2018
Bug
Bug No known bugs
Function Documentation
InitEthernet()
void InitEthernet (void)
Initialization routine for use of the ENC28J60 in this project.
Returns
void
Definition at line 256 of file Ethernet.c.
References readBasic().
{
    // First perform a system reset. This will ensure register start with their expected values
    readBasic(SOFT_RESET,SOFT_RESET); // normally read returns something but this will
       serve as a write with fewer operations
    waitMS(50); // give the chip time to restart
    
    nextPacketPtr = RXSTART_INIT;
    
    // Rx start
    RegisterWrite(ERXSTL, RXSTART_INIT); // Low byte first and then high byte
    RegisterWrite(ERXSTH, RXSTART_INIT >> 8);
    
    // Now set the current receive pointer address
    RegisterWrite(ERDPTL, RXSTART_INIT);
    RegisterWrite(ERDPTH, RXSTART_INIT >> 8); // Again, low byte first
    
    // RX end
    RegisterWrite(ERXNDL, RXSTOP_INIT & 0xFF); // doing the 0xFF will trim off the higher
       byte
    RegisterWrite(ERXNDH, RXSTOP_INIT >> 8);
    
    // TX Start
    RegisterWrite(ETXSTL, TXSTART_INIT & 0xFF);
    RegisterWrite(ETXSTH, TXSTART_INIT >> 8);
    
    // TX end
    RegisterWrite(ETXNDL, TXSTOP_INIT & 0xFF);
    RegisterWrite(ETXNDH, TXSTOP_INIT >> 8);
    
    // Now configure the packet filters
    // Everything will be filtered with Unicast
    RegisterWrite(ERXFCON, ERXFCON_ANDOR); // have no filters for now
    //RegisterWrite(ERXFCON, ERXFCON_UCEN | ERXFCON_ANDOR);
    // The above line will ignore all packets which don't have the destination address
    // matching this device's MAC address
    
    // Now enable the MAC and other features
    // This will enable the MAC to receive packets
    // allow MAC to transmit pause control frame
    // and inhibit transmission when pause control frames are received
    RegisterWrite(MACON1, MACON1_MARXEN | MACON1_TXPAUS | MACON1_RXPAUS);
    RegisterWrite(MACON2, 0); // this will cause the MAC to enter "normal operation" as
       per the data sheet p61
    //writeBasic(BIT_FIELD_SET, MACON3,MACON3_FRMLNEN); // This will check to make sure that the frame
       length is what it said it was going to be and not impact the others
    
    // Now do Inter-Packet gap (not back-to-back)
    RegisterWrite(MAIPGL, 0x12); // This was what the data sheet recommended (p34)
    RegisterWrite(MAIPGH, 0x0C); // Also what the data sheet recommended
    
    // Now write the MAC Address to the device
    // Note, the ENC28J60 is byte backwards, at least that is the consensus on the Internet
    RegisterWrite(MAADR5, ESB_mac[0]);
    RegisterWrite(MAADR4, ESB_mac[1]);
    RegisterWrite(MAADR3, ESB_mac[2]);
    RegisterWrite(MAADR2, ESB_mac[3]);
    RegisterWrite(MAADR1, ESB_mac[4]);
    RegisterWrite(MAADR0, ESB_mac[5]);
    
    // Now prevent loop back of transmitted frames
    PhyWrite(PHCON2, PHCON2_HDLDIS | PHCON2_FRCLINK);
    
    // enable packet reception
    writeBasic(BIT_FIELD_SET, ECON1, ECON1_RXEN);
    
    // now enable the interrupt flags
    writeBasic(BIT_FIELD_SET, EIE, EIE_PKTIE | EIE_TXIE | EIE_TXERIE | EIE_RXERIE);
    // The above line will enable the interrupt flags for Receive Packet Pending, Transmit, Transmit error,
       and receive packet error
    
}
InitPhy()
void InitPhy (void)
Initialization routine for using the PHY module of the ENC18J60, mostly sets LED blink patterns.
Returns
void
Definition at line 209 of file Ethernet.c.
References PhyWrite().
{
    // Turn the LEDs on
    PhyWrite(PHLCON, LED_on); // Turn both LEDs on
    waitMS(500);
    // Turn the LEDs off
    PhyWrite(PHLCON, LED_off);
    waitMS(500);
    
    // Turn the LEDs back on
    PhyWrite(PHLCON, LED_on);
    waitMS(500);
    
    // Turn LEDs off again
    PhyWrite(PHLCON, LED_off);
    waitMS(500);
    
    // Set the LEDs for normal operation
    // This means that LEDA (green) will correspond to link status
    // And LEDB (yellow) will correspond to receive/transmit
    PhyWrite(PHLCON, LED_normal);
    waitMS(100); // The example code has this in here, don't know if I really
       need it
}
loadData()
uint8_t loadData (uint8_t * fullMessage, uint8_t * message, uint8_t len)
Places data from temporary string into the final array which will be sent to the ENC28J60.
Parameters
in fullMessage Final array which will be sent to the ENC28J60
in message Original and temporary array containing the user's message to sent
in len The length of the sub array of message that is wanting to be sent
Returns
void
Definition at line 438 of file Ethernet.c.
{
    uint8_t i = 0;
    
    // First load the length of the message
    fullMessage[LEN_INDEX] = len + 14;
    fullMessage[LEN_INDEX + 1] = 0; // Since I know the length will be much less than 256
    
    // Next load the MAC Addresses into the full message
    transmitHeader(fullMessage);
    
    // Now load the data from the message into the full message
    while (i < len)
    {
        fullMessage[LEN_INDEX + 2 + i] = message[i];
        i++;
    }
    return (14 + len);
}
packetRecieve()
uint16_t packetRecieve (uint8_t max_length, uint8_t * packets)
Receives packet of information which is waiting in the buffer.
Parameters
in max_length The maximum length (in bytes) that will be read
out packets Array for where to place the data which is sitting in the buffer
Returns
void
Definition at line 363 of file Ethernet.c.
References RegisterRead().
{
    uint16_t rxstat;
    uint16_t len;
    
    // Check to see if a packet has been received, if not, then return
    if (!RegisterRead(EPKTCNT))
        return(0);
        
    // Set the read pointer to the start of the received packet
    RegisterWrite(ERDPTL, nextPacketPtr);
    RegisterWrite(ERDPTH, nextPacketPtr >> 8);
    
    // Read the next packet pointer (see page 43 in data sheet)
    nextPacketPtr = readBasic(READ_BUF_MEM, 0);
    nextPacketPtr |= readBasic(READ_BUF_MEM, 0) << 8;
    // Reading from the memory buffer automatically increments to the next byte
    
    // read the packet length
    len = readBasic(READ_BUF_MEM, 0);
    len |= readBasic(READ_BUF_MEM, 0) << 8;
    // in the example, 4 is subtracted from this but I don't have CRC checking implemented since I don't
       think it is necessary
    
    // read the receive status
    rxstat = readBasic(READ_BUF_MEM, 0);
    rxstat |= readBasic(READ_BUF_MEM, 0) << 8;
    
    // limit the receive length
    if (len > max_length)
        len = max_length;
        
    // check for symbol errors
    if (!(rxstat & 0x80)){
        // this is an invalid packet
        len = 0;
    }
    else{
        readBuffer(len, packets);
    }
    
    // move the RX pointer to the start of the next received packet
    // This frees the memory we just read out
    RegisterWrite(ERXRDPTL, nextPacketPtr);
    RegisterWrite(ERXRDPTH, nextPacketPtr >> 8);
        
    // decrement the packet counter indicate we are done with this packet
    writeBasic(BIT_FIELD_SET, ECON2, ECON2_PKTDEC);
    return(len);
}
packetSend()
void packetSend (uint8_t len, uint8_t * packet)
Sends a packet of information using the Ethernet module.
Parameters
in len Entire length of the packet
in packet Array containing the data for the packet
Returns
void
Definition at line 331 of file Ethernet.c.
References RegisterWrite().
{
    // Set the write pointer to start of transmit buffer area
    RegisterWrite(EWRPTL, TXSTART_INIT & 0xFF);
    RegisterWrite(EWRPTH, TXSTART_INIT >> 8);
    
    // Set the TXND pointer to correspond to the packet size given
    RegisterWrite(ETXNDL, (TXSTART_INIT + len) & 0xFF);
    RegisterWrite(ETXNDH, (TXSTART_INIT + len) >> 8);
    
    // write per-packet control byte (0x00 means use macon3 settings)
    writeBasic(WRITE_BUF_MEM, 0, 0x00); // 0 for address because 0x7A is already in the first
       argument
    
    // copy the packet into the transmit buffer
    writeBuffer(len, packet);
    
    // send the contents of the transmit buffer onto the network
    writeBasic(BIT_FIELD_SET, ECON1, ECON1_TXRTS);
    
    // Reset the transmit logic problem. See Rev. B4 Silicon Errata point 12.
    if((RegisterRead(EIR) & EIR_TXERIF))
    {
        writeBasic(BIT_FIELD_CLR, ECON1, ECON1_TXRTS);
    }
}
PhyRead()
uint16_t PhyRead (uint8_t address)
Reads from a register location from the PHY module within the ENC28J60.
Parameters
in address Name of the register to read from
Returns
uint16_t The value within the specified register
Definition at line 164 of file Ethernet.c.
References RegisterWrite().
{
    // First I need to set the PHY register address
    RegisterWrite(MIREGADR, address);
    
    // Now set the MICMD.MIIRD bit
    writeBasic(BIT_FIELD_SET, MICMD, MICMD_MIIRD);
    
    // now wait for at least 10.24 us
    waitMS(15);
    
    // Now clear the MIIRD bit
    writeBasic(BIT_FIELD_CLR, MICMD, MICMD_MIIRD);
    
    uint16_t data = 0;
    data |= RegisterRead(MIRDL);
    data |= (RegisterRead(MIRDH) << 8);
    
    return data;
}
PhyWrite()
void PhyWrite (uint8_t address, uint16_t data)
Writes to a register location in the PHY module within the ENC28J60.
Parameters
in address Name of the register to write to
in data 16 bit value which will be written into the register
Returns
void
Definition at line 191 of file Ethernet.c.
References RegisterWrite().
{
    // first need to set the PHY register address
    RegisterWrite(MIREGADR, PHLCON);
    // Write the PHY data
    RegisterWrite(MIWRL, data & 0xFF);
    RegisterWrite(MIWRH, data >> 8);
        
    // now need to wait for 10.24 us, but I will just poll for the end of the waiting time after 1 waiting
       cycle
    while(RegisterRead(MISTAT) & MISTAT_BUSY)
        waitMS(15);
    
}
readBasic()
uint8_t readBasic (uint8_t op, uint8_t address)
Performs a low level read operation of a register.
Parameters
in op This will be implemented in the function call to be the register read op code
in address This is 5 bits which correspond to the desired register
Returns
uint8_t
Definition at line 25 of file Ethernet.c.
{
    CSACTIVE;
    // Now tell the chip that I am trying to read
    SPDR = op | (address & ADDR_MSK); // this will make it so only the last 5 bits are preserved of the
       address
    waitSPI(); // wait for the SPI interrupt flag to be set
    
    // read the data
    SPDR = 0;
    waitSPI();
     
    // If the address is a MAC or MII register then the byte which will be picked up by SPRD
    // will be dummy data
    if (address & 0x80){
        SPDR = 0;
        waitSPI();
    }
    CSPASSIVE; // raise the CS line
    return SPDR;
}
readBuffer()
void readBuffer (uint8_t len, uint8_t * data)
Reads a specified number of bytes from the buffer and stores them in an array.
Parameters
in len The number of bytes to be read from the buffer
out data pointer to the location data should be written to
Returns
void
Definition at line 71 of file Ethernet.c.
{
    // First pull the CS line low
    CSACTIVE;
    // Now issue the read buffer memory command
    SPDR = READ_BUF_MEM;
    waitSPI(); // Now wait for the message to be sent
    
    while(len)
    {
        len--;
        SPDR = 0; // Just give the register some data so that it begins the transmission
        waitSPI();
        *data = SPDR;
        data++;
    }
    *data = 0; // Conclude the data with a null terminator
    CSPASSIVE; // Raise the CS line to stop the transmission
    
}
readTX_StatusVec()
void readTX_StatusVec (uint8_t * Status)
Reads the transmit status vector from the address which is the end of the transmit buffer + 1.
Parameters
out Status Array by which to copy the 7 bytes of the status vector
Returns
void
Definition at line 462 of file Ethernet.c.
References RegisterRead().
{
    // This will read the 7 bytes which are located at ETXND+1
    // First need to save the location of the read pointer
    uint16_t savePointer = RegisterRead(ERDPTL);
    savePointer |= RegisterRead(ERDPTH) << 8;
    
    // Now get the current value of ETXND
    uint16_t curTX_end = RegisterRead(ETXNDL);
    curTX_end |= RegisterRead(ETXNDH) << 8;
    curTX_end++;
    
    // Now set the read pointer
    RegisterWrite(ERDPTL, curTX_end & 0xFF);
    RegisterWrite(ERDPTH, curTX_end >> 8);
    
    // Now read the buffer 7 times
    readBuffer(7, Status);
    
    // Now put the read pointer back
    RegisterWrite(ERDPTL, savePointer & 0xFF);
    RegisterWrite(ERDPTH, savePointer >> 8);
    
}
RegisterRead()
uint8_t RegisterRead (uint8_t address)
Reads the value for a specified register in memory for the ENC28J60.
Parameters
in address the memory register by which to do the read operation
Returns
uint8_t The value within the specified register
Definition at line 137 of file Ethernet.c.
References readBasic(), and setBank().
{
    // first set the bank
    setBank(address);
    // Now read the data from the register
    return readBasic(READ_CONTROL_REG, address);
}
RegisterWrite()
void RegisterWrite (uint8_t address, uint8_t data)
Writes a byte of data to a specified register location for the ENC28J60.
Parameters
in op
in address
Returns
void
Definition at line 151 of file Ethernet.c.
References setBank(), and writeBasic().
{
    // First set the bank
    setBank(address);
    // now write the data to the register
    writeBasic(WRITE_CONTROL_REG, address, data);
}
setBank()
void setBank (uint8_t address)
Set the current bank to that which corresponds to that of a specified register for the ENC28J60.
Parameters
in address Name of the register by which to change the bank to
Returns
void
Definition at line 121 of file Ethernet.c.
{
    // This will set the bank to whichever bank *address* is in
    if (((address & BANK_MASK) >> 5) != bankNumber){
        writeBasic(BIT_FIELD_CLR, ECON1, (ECON1_BSEL0 | ECON1_BSEL1)); // First clear the
       bank from the relevant register
        writeBasic(BIT_FIELD_SET, ECON1, (address & BANK_MASK) >> 5); // Get the 2 bits by
       themselves and then shift to have it read the correct number
        bankNumber = (address & BANK_MASK) >> 5; // Save the bank number for
       future comparison
    }
    
}
transmitHeader()
void transmitHeader (uint8_t * buffer)
Place the proper header bytes to the beginning of the array which will hold the message.
Parameters
in buffer Array of where to place the header bytes
Returns
void
Definition at line 418 of file Ethernet.c.
{
    uint8_t i=0;
    //copy the destination mac from the source and fill my mac into src
    while(i < 6)
    {
        buffer[DEST_MAC + i] = ECU_mac[SRC_MAC + i];
        buffer[SRC_MAC + i] = ESB_mac[i];
        i++;
    }
}
waitMS()
void waitMS (uint16_t msec)
Waits for a designated number of milliseconds.
Parameters
in msec Value of milliseconds that are wanting to be waited for
Returns
void
Waits for a designated number of milliseconds.
Parameters
in msec Number of milliseconds that are desired to be delayed for
Returns
void
Definition at line 166 of file ESB_funcs.c.
References assign_bit(), and bit_is_clear.
{
    // This function utilizes timer 0 and a sequence of delay loops to delay for the desired time
    TCNT0 = 5;
    // begin the timer
    TCCR0B |= (1 << CS01) | (1 << CS00); // this will start the timer with a prescalar of 64
    for (uint16_t i = 0; i < msec; i++){
        while(bit_is_clear(TIFR0, TOV0));
        TIFR0 |= (1 << TOV0); // Clear the overflow flag by writing a 1 to it
    }
    assign_bit(&TCCR0B, CS01, 0);
    assign_bit(&TCCR0B, CS00, 0); // Turn off the timer
}
writeBasic()
void writeBasic (uint8_t op, uint8_t address, uint8_t data)
Performs a low level write operation of a register.
Parameters
in op This would be implemented in the function call to be the register write op code
in address This is the 5 bits which correspond to the desired register
in data This is the byte of data to be written to the register
Returns
void
Definition at line 53 of file Ethernet.c.
{
    CSACTIVE;
    SPDR = op | (address & ADDR_MSK); // this will tell the Ethernet chip where to write the data
    waitSPI();
    
    // write the data
    SPDR = data;
    waitSPI();
    CSPASSIVE;
}
writeBuffer()
void writeBuffer (uint8_t len, uint8_t * data)
Writes a specified number of bytes into the buffer memory.
Parameters
in len Number of bytes to be written into the buffer memory
in data Array of the data to write into the buffer
Returns
void
Definition at line 98 of file Ethernet.c.
{
    CSACTIVE; // First pull the CS line low
    SPDR = WRITE_BUF_MEM; // Issue the write buffer command
    waitSPI();
    
    while (len)
    {
        len--;
        SPDR = *data; // Send the current byte of data
        waitSPI();
        data++;
        
    }
    CSPASSIVE; // Raise the CS line to stop the transmission
    
}