C:/Users/nickm/Documents/GitHub/ACES_ECU/ACES_ECU/Communication.c File Reference
Implementation for the functions relating to the communication of the ECU/ESB and ECU/Windows GUI.
#include <avr/io.h>
#include <avr/interrupt.h>
#include <string.h>
#include `ECU_funcs.h`
Functions
void sendToESB (uint8_t len)
Transmits data between the ECU and ESB.
void ESB_Connect (void)
Establishes the connection between the ECU and ESB.
void GUI_Connect (void)
Establishes the connection between the ECU and Windows GUI.
void sendToLaptop (void)
Transmits periodic data between the ECU and Windows GUI.
ISR (USART0_RX_vect)
Interrupt Service Routine for when a message has been received from the Windows GUI.
ISR (USART1_RX_vect)
void packageMessage (void)
void repeatCommand (void)
Requests the Windows GUI to repeat the last sent command.
void i2c_Start (unsigned char address)
void i2c_Stop (void)
void i2c_write (unsigned char data)
unsigned char i2c_read (unsigned char ack)
void loadESBData (void)
Detailed Description
Implementation for the functions relating to the communication of the ECU/ESB and ECU/Windows GUI.
Author
Nick Moore March 16, 2018
Bug
Bug No known bugs.
Note
Add notes here
Function Documentation
ESB_Connect()
void ESB_Connect (void)
Establishes the connection between the ECU and ESB.
This performs the following functions:
1) Prepares the ECU's password for transmission 2) Sends the password to the ESB 3) Awaits the correct return password from the ESB 4) repeats steps 2-4 until the proper return password is received
Parameters
void
Returns
void
Definition at line 53 of file Communication.c.
References ESBtransmit, and sendToESB().
{
    ESBtransmit[0] = 'A';
    ESBtransmit[1] = 'C';
    ESBtransmit[2] = 'E';
    ESBtransmit[3] = 'S';
    sendToESB(4);
}
GUI_Connect()
void GUI_Connect (void)
Establishes the connection between the ECU and Windows GUI.
This performs the following functions:
1) Prepares the ECU's password for transmission 2) Sends the password to the Windows GUI
Parameters
void
Returns
void
Definition at line 73 of file Communication.c.
References connected_GUI, and doTransmit.
{
    char message[] = "DALE";
    for (uint8_t i = 0; i < 4; i++){ // This will also send the terminator
        /* Wait for empty transmit buffer */
        while (!(UCSR0A & (1<<UDRE0)));
        /* Put data into buffer, sends the data */
        UDR0 = message[i];
    }
    connected_GUI = 1;
    doTransmit = -1;
}
ISR()
ISR (USART0_RX_vect)
Interrupt Service Routine for when a message has been received from the Windows GUI.
This performs the following functions:
1) Sets the newCommand variable based on which type of command is being received 2) Awaits the second a later bytes depending on which type of command is being received 3) If a received command deviated from the expected format, the command is asked to be repeated
commandMode = 0 handles all undefined behavior commandMode = 1 corresponds to the GUI ordering the ECU to do something (starting or stopping) commandMode = 2 corresponds to the GUI requesting that the throttle be changed to a specified value (in percent of max)
Parameters
void
Returns
void
Definition at line 191 of file Communication.c.
References assign_bit(), commandMode, connect_count, connected_GUI, GUI_Connect(), hasInterrupted, newCommand, repeatCommand(), sendToLaptop(), shutdown(), startup(), throttle(), and throttle_per.
{
    // This will automatically clear the interrupt flag
    char data = UDR0;
    hasInterrupted = 1; // Set this flag so that the ESBCommand function
       knows if it has been interrupted or not
    if (newCommand){
        newCommand = 0; // reset this so that the commandMode cannot change
       until the command string is done
        if (data == 'A'){
            connect_count = 1;
            newCommand = 1;
        }
        else if (data == 'C' && connect_count == 1){
            connect_count++;
            newCommand = 1;
        }
        else if (data == 'E' && connect_count == 2){
            connect_count++;
            newCommand = 1;
        }
        else if (data == 'S' && connect_count == 3){
            connect_count++;
            GUI_Connect();
            newCommand = 1;
        }
        else if (data == 'O'){
            commandMode = 1; // This means the GUI is ordering the ECU to do
       something
        }
        else if (data == 'T'){
            commandMode = 2; // This means the GUI is requesting the ECU change
       the throttle to a specified value
        }
        else if (data == 'K'){ // This means the GUI is sending a confirmation message for
       receiving the usual data transfer
            newCommand = 1;
            // stop timer 4
            assign_bit(&TCCR4B, CS41, 0);
            assign_bit(&TCCR4B, CS40, 0); // turn off the timer
            TCNT4 = 40536; // reset the timer register
        }
        else if (data == 'R'){ // This means that the data needs to be sent to the GUI one more time
            newCommand = 1;
            sendToLaptop(); // this will just use what ever the values of the data currently
       are
        }
        else{
            commandMode = 0; // This will handle all undefined behavior
            if (!connected_GUI)
                newCommand = 1; // This was found to work during debugging as there is a 0
       waiting in the buffer
        }
    }
    else if (connected_GUI) {
        newCommand = 1;
        switch (commandMode){
            case 0:
                repeatCommand(); // repeat the command because something got screwed
       up This isn't right because I don't do it over spi, do it over USART
                break;
            case 1:
                if (data == 'S'){ // GUI wants the engine to stop
                    shutdown();
                }
                else if (data == 'r'){ // GUI wants the engine to start
                    startup();
                }
                else{
                    repeatCommand(); // undefined behavior, ask GUI to repeat
                }
                break;
            case 2:
                throttle_per = data; // GUI wants the throttle to the value specified by
       data
                throttle();
                break;
        }
        newCommand = 1; // reset this so that a new command will be accepted
       in the way that is expected
        
    }
}
repeatCommand()
void repeatCommand (void)
Requests the Windows GUI to repeat the last sent command.
This performs the following functions:
1) Sends the char to the GUI which signals a command repetition is required
Parameters
void
Returns
void
Definition at line 349 of file Communication.c.
{
    /* Wait for empty transmit buffer */
    while (!(UCSR0A & (1<<UDRE0)));
    
    /* Put data into buffer, sends the data */
    UDR0 = 'V';
    // Will have to see in unit testing how long this takes to get the response from the GUI
}
sendToESB()
void sendToESB (uint8_t len)
Transmits data between the ECU and ESB.
This performs the following functions:
1) Pulls the SS line for the ESB low, this will cause the ESB to listen to the com line 2) Fills the specified data into the transmit buffer 3) Waits for the data to be received from the ESB 4) Pulls the SS line high to end communication with ESB for that byte
Parameters
char The byte that is going to be sent to the ESB
Returns
char The received byte from the ESB
Definition at line 28 of file Communication.c.
References ESBtransmit.
{
    // this will send the number of character in ESBmessage up to len
    cli();
    for(uint8_t i = 0; i < len; i++)
    {
        while (!(UCSR1A & (1<<UDRE1)));
        /* Put data into buffer, sends the data */
        UDR1 = ESBtransmit[i];
    }
    sei();
}
sendToLaptop()
void sendToLaptop (void)
Transmits periodic data between the ECU and Windows GUI.
This performs the following functions:
1) Prepares the message to send to the Windows GUI 2) Loops through this message, sending it one byte at a time
Parameters
void
Returns
void
Definition at line 96 of file Communication.c.
References calculateParity(), connected_ESB, ECU_temp, EGT, ESB_temp, glow_plug, Hall_effect, massFlow, opMode, and voltage.
{
    //loadESBData();
    dummyData(); // remove this later
    // This function will be responsible for packaging and sending the desired data to the Windows GUI
    char message[28]; // this is the base length of the message with room for the parity bytes
    // now fill the message
    if (!connected_ESB){
        message[0] = 'b'; // This means that the ESB is not connected or it has lost connection
    }
    else if (opMode == 0){
        message[0] = 'S'; // This means that an engine shutdown is being carried out
    }
    else if(opMode == 1){
        message[0] = 'r'; // This means that an engine startup is in progress
    }
    else if(opMode == 2){
        message[0] = 't'; // This means that a throttle adjustment has been requested and is being
       carried out
    }
    else if(opMode == 4){
        message[0] = 'C'; // This means that the engine is in the cooling mode
    }
    else if(opMode == 5){
        message[0] = 'n'; // The engine is not doing anything
    }
    else if (opMode == 6){
        message[0] = 'g'; // Special shutdown, the EGT is not working properly and there cannot be
       a normal cooling mode
    }
    else if (opMode == 7){
        message[0] = 'N'; // This means that the engine has reached the desired throttle, within
       the error tolerance
    }
    else if (opMode == 9){ // This means that fuel is not flowing when it should be flowing
        message[0] = 'P';
    }
    else if (opMode == 10){
        message[0] = 'I'; // This means that the engine has reached idle
    }
    else if (opMode == 11){
        message[0] = 'c'; // This means that messages from the ECU have failed the parity check
    }
    else if (opMode == 12){
        message[0] = 'R'; // This means that RPM limit has been reached and the engine is shutting
       down
    }
    else if (opMode == 13){
        message[0] = 'T'; // This means the Temperature limit has been reached and the engine is
       shutting down
    }
    else if (opMode == 14){
        message[0] = 's'; // This means that messages from the ESB have failed the parity check
    }
        
    memcpy(message+1,&massFlow,sizeof(float)); // This should fill 1->4 with the float
       value
    memcpy(message+5,&Hall_effect,sizeof(uint16_t)); // This should fill 5->6 with the Hall
       effect sensor value
    memcpy(message+7,&EGT,sizeof(float)); // This should fill 7->8 with the EGT value
    memcpy(message+11,&voltage,sizeof(float)); // this should fill 9->12 with the value of the
       battery voltage
    memcpy(message+15,&glow_plug,sizeof(char)); // This should fill 13 with the glow plug
       on/off
    memcpy(message+16,&ECU_temp,sizeof(float)); // This should fill 14->17 with the
       temperature of the ECU
    memcpy(message+20,&ESB_temp,sizeof(float)); // This should fill 18->21 with the ambient
       temperature of the ESB
    
    // now that the message is made, I need to calculate and populate the parity bytes
    message[24] = calculateParity(message, 0);
    message[25] = calculateParity(message, 6);
    message[26] = calculateParity(message, 12);
    message[27] = calculateParity(message, 18);
    
    // At this point it is advantageous to turn off global interrupts so that this process is not
       interrupted
    cli();
    for (uint8_t i = 0; i < 28; i++){
        /* Wait for empty transmit buffer */
        while (!(UCSR0A & (1<<UDRE0)));
        /* Put data into buffer, sends the data */
        UDR0 = message[i];
    }
    sei(); // Now need to turn global interrupts back on
    // Now start the timer
    
    TCCR4B = (1 << CS42); // start timer 4 with prescalar of 256
}