C:/Users/nickm/Documents/GitHub/ACES_ECU/ACES_ECU/ECU_funcs.h File Reference
Function prototypes, macros, constants, and global variables for ECU microcontroller.
#include <avr/sfr_defs.h>
#include <float.h>
Macros
#define bit_is_set(sfr, bit) (_SFR_BYTE(sfr) & _BV(bit))
Simple function define for testing if the bit is set.
#define bit_is_clear(sfr, bit) (!(_SFR_BYTE(sfr) & _BV(bit)))
Simple function define for testing if the bit is clear.
#define ECU_temp_sensors 0
#define ESB_temp_sensors 0
#define K_factor 91387
Assumed K factor for the flow meter in pulses per liter.
#define density 0.81
Density of the kerosene in g/ml.
#define max_time 0.25
Maximum amount of time for an 8 bit timer with a prescalar of 1024.
#define pump_m 0.382587
Slope for the linear relationship between voltage and mass flow (put in mf, get volts)
#define pump_b 0.195783
Y-intercept for the linear relationship between voltage and mass flow.
#define HCU_present 0
defines if the HCU is present in the current configuration or not, 1 for yes, 0 for no
#define maxRPM 60850
Defines the maximum RPM of the engine.
#define idleRPM 16384
Defines the idle RPM of the engine.
#define SLA_W 0x3E
#define SLA_R 0x3F
#define dec_MSK 0x0C
#define SPI_PORT PORTB
#define normalData 11
#define ESB_timer_val 3036
#define FlowTime 3700
#define XCK1 5
#define UCPHA1 1
#define ESB_SS 0
#define HCU_link 1
#define MOSI 2
#define SCK 1
Functions
void pre_Initial (void)
Performs the waiting cycle until the HCU signals to the ECU to being operating.
void Initial (void)
Initializes the microcontroller for its mainline execution.
void shutdown (void)
Commands the ESB to shutdown and awaits the confirmation code.
void startup (void)
Commands the ESB to startup and awaits the confirmation code.
void throttle (void)
Commands the ESB to adjust the throttle and awaits the confirmation code.
void batVoltage (void)
Measures the voltage on the Lipo battery from the 3 different ADC channels.
void assign_bit (volatile uint8_t *sfr, uint8_t bit, uint8_t val)
Sets the specified bit to the specified value or does nothing if it already set to that.
void sendToESB (uint8_t len)
Transmits data between the ECU and ESB.
void ESB_Connect (void)
Establishes the connection between the ECU and ESB.
void measureFlow (void)
Measures the fuel flow passing through the Flow meter.
void sendToLaptop (void)
Transmits periodic data between the ECU and Windows GUI.
void repeatCommand (void)
Requests the Windows GUI to repeat the last sent command.
void GUI_Connect (void)
Establishes the connection between the ECU and Windows GUI.
void i2c_Start (unsigned char address)
void i2c_Stop (void)
void i2c_write (unsigned char data)
unsigned char i2c_read (unsigned char ack)
void readTempSensor (void)
Accesses memory within the MAX6675 and converts the data into a usable temperature.
char calculateParity (char message[], uint8_t start_index)
Function to calculate the parity byte for a corresponding sequence of 6 bytes.
unsigned char countOnes (unsigned char byte)
Subroutine to count the number of high bits within a designated byte.
void packageMessage (void)
void waitMS (uint16_t msec)
Subroutine which will wait for a given number of milliseconds.
void loadESBData (void)
Variables
xx xx xx xx xx xx xx xx xx
union {
 float f
 unsigned char c [4]
} voltage
Float which contains the current voltage level on the Lipo battery.
char batChannel
Char which keeps track of which ADC channel we are on.
char opMode
Holds the current operational mode of the engine.
uint8_t throttle_per
Char which keeps track of the throttle percentage 0-100.
xx xx xx xx xx xx xx xx xx
union {
 float f
 unsigned char c [4]
} massFlow
Float holding the current mass flow rate.
uint16_t Hall_effect
uint_16 holding the current measurement of the hall effect sensor
float EGT
uint_16 holding the current measurement of the exhaust gas thermocouple
unsigned char glow_plug
unsigned char holding whether or not the glow plug is currently on
uint8_t pulse_count
This will keep track of how many pulses have been seen in the sampling window.
float V_per_pulse
Variable to convert the pulses into a voltage.
uint8_t commandMode
Will keep track of the input format that the ECU will be expecting.
uint8_t newCommand
Will keep track of whether or not it is possible for a new command stream to be coming in.
uint8_t hasInterrupted
Will keep track of whether or not the message to the ESB has been interrupted by the PC.
uint8_t connected_ESB
Will keep track of whether or not the ECU is connected to the windows GUI.
uint8_t connected_GUI
Essentially boolean describing if the ECU is connected to the GUI or not.
char ESBtransmit [11]
Array of data which will be transmitted to the ESB.
char ESBreceive [14]
Array containing the data received from the ESB.
float ECU_temp
Ambient temperature of the ECU.
float ESB_temp
Ambient temperature of the ESB.
uint8_t connect_count
Counter for index into the connection string (The connection string is ACES)
uint8_t newCommand_ESB
Flag which describes if the next received command is the beginning of a new command or the continuation of an old command.
uint8_t ESBreceiveCount
Counter for the received byte in the current message.
int8_t doTransmit
Flag which is used to synchronize when messages are allowed to be sent to the GUI.
Detailed Description
Function prototypes, macros, constants, and global variables for ECU microcontroller.
Control register definitions and function prototypes for the ENC28J60 Ethernet controller.
Author
Nick Moore
Date
March 16, 2018
Bug
Bug No known bugs
Author
Nick Moore
Date
June 21, 2018
Bug
Bug No known bugs
Function Documentation
assign_bit()
void assign_bit (volatile uint8_t * sfr, uint8_t bit, uint8_t val)
Sets the specified bit to the specified value or does nothing if it already set to that.
Parameters
out sfr Pointer to Special Function Register the bit is located in.
in bit Denotes the bit which would like to be changed.
in val The value, either 1 or 0, that the user would like the bit to be after the function call.
Returns
void
Definition at line 104 of file ECU_funcs.c.
{
    if (val) // This is for if I want the value to be a 1
    {
        val = (val << bit);
        *sfr |= val;
    }
    else // This is for if I want the value to be a 0
    {
        val = ~(1 << bit);
        *sfr &= val;
    }
}
batVoltage()
void batVoltage (void)
Measures the voltage on the Lipo battery from the 3 different ADC channels.
This performs the following functions:
1) Measures the ADC voltage on the current ADC channel 2) Combines this result will the current float value of the voltage 3) Changes the ADC channel to the next one in the rotation 0->1->2->0
Parameters
void
Returns
void
Definition at line 25 of file ECU_funcs.c.
References bit_is_set, and voltage.
{
    // first check to see if the conversion has completed
    if (bit_is_set(ADCSRA,ADSC))
        return;
    
    uint8_t low_bits = ADCL;
    uint8_t high_bits = ADCH; // Do the shifting so that there is room made inside
       of the 16 bit register
    uint16_t result = (high_bits << 8) | low_bits;
    
    // Now I need to convert this 16 bit number into an actual temperature
    voltage.f = 3.0 * (float) result; // Convert to float value of the voltage
    voltage.f = voltage.f * (4.96 / 1024.0); // This will return Vin
    
    ADCSRA |= (1 << ADSC); // Start the next conversion
        
}
calculateParity()
char calculateParity (char message[], uint8_t start_index)
Function to calculate the parity byte for a corresponding sequence of 6 bytes.
Parameters
in message Entire message which a subset will be used in order to calculate the parity byte
in start_index Starting index within message for which to calculate the parity byte
Returns
char
Definition at line 196 of file ECU_funcs.c.
References countOnes().
{
    // This will return the parity byte for a message made up of 6 sequential bytes, starting with
       start_index
        char parity = 0;
        
        // first need to get the number of high bits in the first three bytes in the set
        for (unsigned set = 0; set < 2; set++){
            unsigned char count = 0;
            for (unsigned char i = 0; i < 3; i++){
                count += countOnes(message[start_index + set*3 + i]);
            }
            // now that I have the count for this set, I need to take the modulo
            count = count % 16; // Modulo with 16 because I have 4 bits to play with
            
            // now add this into the parity byte
            parity |= count << (4 * set); // this will make it so that bytes 0-2 will take up the LSB of
       the parity byte
        }
        // now copy this byte into memory
        return parity;
}
countOnes()
unsigned char countOnes (unsigned char byte)
Subroutine to count the number of high bits within a designated byte.
Parameters
in byte The byte by which to calculate the number of high bits within
Returns
unsigned char
Definition at line 222 of file ECU_funcs.c.
{
    unsigned char count = 0;
    while (byte)
    {
        count += byte & 1; // this was essentially lifted from geeksforgeeks.com
        byte >>= 1;
    }
    return count;
}
ESB_Connect()
void ESB_Connect (void)
Establishes the connection between the ECU and ESB.
This performs the following functions:
1) Prepares the ECU's password for transmission 2) Sends the password to the ESB 3) Awaits the correct return password from the ESB 4) repeats steps 2-4 until the proper return password is received
Parameters
void
Returns
void
Definition at line 53 of file Communication.c.
References ESBtransmit, and sendToESB().
{
    ESBtransmit[0] = 'A';
    ESBtransmit[1] = 'C';
    ESBtransmit[2] = 'E';
    ESBtransmit[3] = 'S';
    sendToESB(4);
}
GUI_Connect()
void GUI_Connect (void)
Establishes the connection between the ECU and Windows GUI.
This performs the following functions:
1) Prepares the ECU's password for transmission 2) Sends the password to the Windows GUI
Parameters
void
Returns
void
Definition at line 73 of file Communication.c.
References connected_GUI, and doTransmit.
{
    char message[] = "DALE";
    for (uint8_t i = 0; i < 4; i++){ // This will also send the terminator
        /* Wait for empty transmit buffer */
        while (!(UCSR0A & (1<<UDRE0)));
        /* Put data into buffer, sends the data */
        UDR0 = message[i];
    }
    connected_GUI = 1;
    doTransmit = -1;
}
Initial()
void Initial (void)
Initializes the microcontroller for its mainline execution.
This performs the following functions:
1) Initializes the PORT data directions. 0 for input and 1 for output
2) Initializes the asynchronous communication with the Windows GUI
3) Initializes the SPI communication with the ESB
4) Initializes the I2C communication with the on board temperature sensors
5) Initializes the ADC for the Lipo battery voltage measurements
6) Enable global interrupts
7) Enable a timer for the ECU command cycle and start the timer
Parameters
void
Returns
void
Definition at line 49 of file Initial_funcs.c.
{
    DDRD |= (1 << XCK1); // Enable the SPI output pin for output. This puts the ECU in master
       mode for SPI
    
    UBRR0 = 12; // With a 16 MHz clock this will make a baud rate of 76800 (error of 0.16%)
    
    // The next things that need to be set are as follows (reference page 220 in datasheet)
    // 1) Enable receive interrupts
    // 2) Enable receiver
    // 3) Enable transmitter
    UCSR0B = (1 << RXCIE0) | (1 << RXEN0) | (1 << TXEN0);
    
    // Now set the framing information
    // I want the following things
    // 1) Asynchronous USART
    // 2) No Parity
    // 3) 1 Stop bit
    // 4) 8 bit character size
    UCSR0C = (1 << UCSZ01) | (1 << UCSZ00); // Now the USART should be ready to receive
        
    
    UBRR1 = 12; // With a 16 MHz clock this will make a baud rate of 76800 (error of 0.16%)
    // This is the same process as with communication with the GUI
    
    UCSR1B = (1 << RXCIE1) | (1 << RXEN1) | (1 << TXEN1);
    
    // Now set the framing information
    // I want the following things
    // 1) Asynchronous USART
    // 2) No Parity
    // 3) 1 Stop bit
    // 4) 8 bit character size
    UCSR1C = (1 << UCSZ11) | (1 << UCSZ10); // Now the USART should be ready to receive
    newCommand_ESB = 1;
    ESBreceiveCount = 0;
    waitMS(50);
    while (!connected){ // wait until connected with the ESB
        ESB_Connect();
        waitMS(10);
    }
                
    
    // First set the bit rate and prescalar registers for a clock rate of 200 kHz (this is right in the
       middle of the sensor's range)
    DDRD |= (1 << PD0); // this will make the clock line an output
    TWBR = 8; // Bit rate register
    assign_bit(&TWSR, TWPS0, 0);
    assign_bit(&TWSR, TWPS1, 0); // this makes a prescalar of 1
    // Probably don't need to make these assignments but I am just making it explicit
    
    // Second enable the interrupts for the Two Wire Interface
    TWCR = (1<<TWEN); // this will clear the interrupt flag and enable the TWI lines.
    // the temp sensor will be read every quarter second
    
    
    
    // The next things that need to be set are as follows
    // 1) The reference for the ADC needs to be set to the external AREF
    // 2) The channel for ADMUX needs to be channel 0
    // 3) The ADC needs to be enabled without interrupts
    // 4) Division factor for the ADC needs to be set to 128 to keep the input clock
    // frequency between 50kHz and 200kHz
    
    ADMUX = (1 << REFS0);
    ADCSRA = (1 << ADEN) | (1 << ADPS0) | (1 << ADPS1) | (1 << ADPS2);
    batChannel = 0;
    sei();
     
    
    // The next things that need to be set are as follows
    // 1) Timer 1 needs a prescalar of 64 and timer register of 3036 for time of 0.25 sec, for
       regulating communication with the ESB
    // 2) Timer 3 needs a prescalar of 64 and timer register if 3036
    // 3) Timer 4 and 5 needs to have interrupts enabled and create a 1 second timer
    TCNT1 = 3036;
    TCNT3 = FlowTime; // The flow meter timer does not need interrupts since it will be polled
    
    // The TIFR1 register and TOV1 flag are the overflow flag for timer1
    TCCR1B = (1 << CS11) | (1 << CS10); // start timer 1 with prescalar of 64
    TCNT4 = 34286; // coupled with a prescalar of 256, this will make a 0.5 second
       timer
    TCNT5 = 40536;
    TIMSK4 = (1 << TOIE4); // enable overflow interrupts for the GUI communication timer
    TIMSK5 = (1 << TOIE5); // enable overflow interrupts for the ESB communication timer
    TCNT5 = ESB_timer_val; // loads Timer 5 with a value that will make a 1 second timer
    
    // Begin the first conversion for the ADC
    ADCSRA |= (1 << ADSC);
    
    massFlow.f = 0.0;
     
    // Now configure the external interrupts for the Flow meters
    EICRA = (1 << ISC20) | (1 << ISC21); // This will enable rising edge interrupts on INT2, see page
       110 in datasheet
    assign_bit(&DDRD, INT2, 0); // Configure the PD2 pin as an input so that it can
       receive the signals
     
     
    // Now configure the global variables for the flow meter
    float pulse_flow = (density) * K_factor * max_time / 1000; // number of pulses
       expected per g/sec
    V_per_pulse = pump_m / pulse_flow; // number of volts per pulse
    opMode = 0;
    newCommand = 1;
    
    // Initialize all of the data values to zero
    massFlow.f = 0;
    Hall_effect = 0;
    EGT = 0;
    glow_plug = 0;
    voltage.f = 0;
    doTransmit = 0;
    
    
}
measureFlow()
void measureFlow (void)
Measures the fuel flow passing through the Flow meter.
This performs the following functions:
1) If the flow meter measurement has not started, it enables the appropriate interrupts and returns 2) If the flow meter measurement is in progress, it simply returns 3) If the flow meter measurement has concluded, it calculates the recorded pulses
Parameters
void
Returns
void
Definition at line 54 of file ECU_funcs.c.
References assign_bit(), bit_is_clear, and pulse_count.
{
    pulse_count = 0;
    EIMSK |= (1 << INT2); // enable the external interrupts
    
    // Now start Timer3 to run for 0.25 sec
    TCCR3B |= (1 << CS31) | (1 << CS30);
    
    while (bit_is_clear(TIFR3, TOV3)); // hog execution until the overflow flag has been
       set
    TIFR3 |= (1 << TOV3); // clear the interrupt flag
    
    // now disable the external interrupt
    assign_bit(&EIMSK, INT2, 0);
    
    // Now turn off Timer 3
    assign_bit(&TCCR3B, CS31, 0);
    assign_bit(&TCCR3B, CS30, 0);
    
    // Now reset the value inside of the TIMER3 register
    TCNT3 = FlowTime; // This will allow the timer to run for 0.25 sec once the prescalars are restored
    
    // Now need to convert the pulses detected into an actual flow rate
    //massFlow.f = V_per_pulse * (float) pulse_count;
    //massFlow.f = (massFlow.f - pump_b) / pump_m;
    // now set the doTransmit flag
    if (doTransmit < 1){
        doTransmit++;
    }
}
pre_Initial()
void pre_Initial (void)
Performs the waiting cycle until the HCU signals to the ECU to being operating.
This performs the following functions:
1) Waits until the connection pin between the HCU and ECU is driven high
Parameters
void
Returns
void
Definition at line 22 of file Initial_funcs.c.
{
    DDRC |= (0 << HCU_link); // set this pin for input
    while (bit_is_clear(PINC, HCU_link)); // just wait until the HCU tells the ECU to wake
       up
}
readTempSensor()
void readTempSensor (void)
Accesses memory within the MAX6675 and converts the data into a usable temperature.
Parameters
void
Returns
void
Definition at line 152 of file ECU_funcs.c.
{
    i2c_Start(SLA_W); // this will write the temp address to the register on the sensor
    i2c_write(0x05); // this references the temperatures location in memory
    
    // now restart I2C so that it will be configured for reading the temperature
    i2c_Start(SLA_R);
    
    // now read the upper and lower bytes
    unsigned char upper = i2c_read(1); // this will send the acknowledged bit
    unsigned char lower = i2c_read(0); // this will send the not acknowledged bit
    i2c_Stop();
    
    // now process the data into a usable temperature
    //First Check flag bits
    if ((upper & 0x80) == 0x80){ //TA >= TCRIT
    }
    
    if ((upper & 0x40) == 0x40){ //TA > TUPPER
    }
    
    if ((upper & 0x20) == 0x20){ //TA < TLOWER
    }
    
    upper = upper & 0x1F; //Clear flag bits
    uint8_t decimal = (lower & dec_MSK) >> 2;
    if ((upper & 0x10) == 0x10){ //TA < 0°C
        upper = upper & 0x0F; //Clear SIGN
        ECU_temp = (float)(256 - ((upper << 4) + (lower >> 4)));
        ECU_temp -= (0.25 * decimal);
    }
    else { //TA >= 0°C
        ECU_temp = (float)((upper << 4) + (lower >> 4)); //Temperature = Ambient Temperature
       (°C)
        ECU_temp += (0.25 * decimal);
    }
}
repeatCommand()
void repeatCommand (void)
Requests the Windows GUI to repeat the last sent command.
This performs the following functions:
1) Sends the char to the GUI which signals a command repetition is required
Parameters
void
Returns
void
Definition at line 349 of file Communication.c.
{
    /* Wait for empty transmit buffer */
    while (!(UCSR0A & (1<<UDRE0)));
    
    /* Put data into buffer, sends the data */
    UDR0 = 'V';
    // Will have to see in unit testing how long this takes to get the response from the GUI
}
sendToESB()
void sendToESB (uint8_t len)
Transmits data between the ECU and ESB.
This performs the following functions:
1) Pulls the SS line for the ESB low, this will cause the ESB to listen to the com line 2) Fills the specified data into the transmit buffer 3) Waits for the data to be received from the ESB 4) Pulls the SS line high to end communication with ESB for that byte
Parameters
char The byte that is going to be sent to the ESB
Returns
char The received byte from the ESB
Definition at line 28 of file Communication.c.
References ESBtransmit.
{
    // this will send the number of character in ESBmessage up to len
    cli();
    for(uint8_t i = 0; i < len; i++)
    {
        while (!(UCSR1A & (1<<UDRE1)));
        /* Put data into buffer, sends the data */
        UDR1 = ESBtransmit[i];
    }
    sei();
}
sendToLaptop()
void sendToLaptop (void)
Transmits periodic data between the ECU and Windows GUI.
This performs the following functions:
1) Prepares the message to send to the Windows GUI 2) Loops through this message, sending it one byte at a time
Parameters
void
Returns
void
Definition at line 96 of file Communication.c.
References calculateParity(), connected_ESB, ECU_temp, EGT, ESB_temp, glow_plug, Hall_effect, massFlow, opMode, and voltage.
{
    //loadESBData();
    dummyData(); // remove this later
    // This function will be responsible for packaging and sending the desired data to the Windows GUI
    char message[28]; // this is the base length of the message with room for the parity bytes
    // now fill the message
    if (!connected_ESB){
        message[0] = 'b'; // This means that the ESB is not connected or it has lost connection
    }
    else if (opMode == 0){
        message[0] = 'S'; // This means that an engine shutdown is being carried out
    }
    else if(opMode == 1){
        message[0] = 'r'; // This means that an engine startup is in progress
    }
    else if(opMode == 2){
        message[0] = 't'; // This means that a throttle adjustment has been requested and is being
       carried out
    }
    else if(opMode == 4){
        message[0] = 'C'; // This means that the engine is in the cooling mode
    }
    else if(opMode == 5){
        message[0] = 'n'; // The engine is not doing anything
    }
    else if (opMode == 6){
        message[0] = 'g'; // Special shutdown, the EGT is not working properly and there cannot be
       a normal cooling mode
    }
    else if (opMode == 7){
        message[0] = 'N'; // This means that the engine has reached the desired throttle, within
       the error tolerance
    }
    else if (opMode == 9){ // This means that fuel is not flowing when it should be flowing
        message[0] = 'P';
    }
    else if (opMode == 10){
        message[0] = 'I'; // This means that the engine has reached idle
    }
    else if (opMode == 11){
        message[0] = 'c'; // This means that messages from the ECU have failed the parity check
    }
    else if (opMode == 12){
        message[0] = 'R'; // This means that RPM limit has been reached and the engine is shutting
       down
    }
    else if (opMode == 13){
        message[0] = 'T'; // This means the Temperature limit has been reached and the engine is
       shutting down
    }
    else if (opMode == 14){
        message[0] = 's'; // This means that messages from the ESB have failed the parity check
    }
        
    memcpy(message+1,&massFlow,sizeof(float)); // This should fill 1->4 with the float
       value
    memcpy(message+5,&Hall_effect,sizeof(uint16_t)); // This should fill 5->6 with the Hall
       effect sensor value
    memcpy(message+7,&EGT,sizeof(float)); // This should fill 7->8 with the EGT value
    memcpy(message+11,&voltage,sizeof(float)); // this should fill 9->12 with the value of the
       battery voltage
    memcpy(message+15,&glow_plug,sizeof(char)); // This should fill 13 with the glow plug
       on/off
    memcpy(message+16,&ECU_temp,sizeof(float)); // This should fill 14->17 with the
       temperature of the ECU
    memcpy(message+20,&ESB_temp,sizeof(float)); // This should fill 18->21 with the ambient
       temperature of the ESB
    
    // now that the message is made, I need to calculate and populate the parity bytes
    message[24] = calculateParity(message, 0);
    message[25] = calculateParity(message, 6);
    message[26] = calculateParity(message, 12);
    message[27] = calculateParity(message, 18);
    
    // At this point it is advantageous to turn off global interrupts so that this process is not
       interrupted
    cli();
    for (uint8_t i = 0; i < 28; i++){
        /* Wait for empty transmit buffer */
        while (!(UCSR0A & (1<<UDRE0)));
        /* Put data into buffer, sends the data */
        UDR0 = message[i];
    }
    sei(); // Now need to turn global interrupts back on
    // Now start the timer
    
    TCCR4B = (1 << CS42); // start timer 4 with prescalar of 256
}
shutdown()
void shutdown (void)
Commands the ESB to shutdown and awaits the confirmation code.
This performs the following functions:
1) Transmits the char to the ESB for the shutdown sequence 2) Waits for the appropriate return message 3) If the function was interrupted part way through by an interrupt, it is restarted
Parameters
void
Returns
void
Definition at line 24 of file Engine_funcs.c.
References ESBreceive, ESBtransmit, sendToESB(), and waitMS().
{
    ESBtransmit[0] = 'S';
    while (ESBreceive[0] != 'K'){ // Loop until the ESB says K
        sendToESB(1);
        waitMS(5);
    }
    ESBreceive[0] = 0; // clear out the first char so that it
       actually transmits
}
startup()
void startup (void)
Commands the ESB to startup and awaits the confirmation code.
This performs the following functions:
1) Transmits the char to the ESB for the startup sequence 2) Waits for the appropriate return message 3) If the function was interrupted part way through by an interrupt, it is restarted
Parameters
void
Returns
void
Definition at line 45 of file Engine_funcs.c.
References ESBreceive, ESBtransmit, sendToESB(), and waitMS().
{
    ESBtransmit[0] = 'r';
    while (ESBreceive[0] != 'K'){
        sendToESB(1);
        waitMS(5);
    }
    ESBreceive[0] = 0; // Change this character so I actually have to receive it in
       the future
    
}
throttle()
void throttle (void)
Commands the ESB to adjust the throttle and awaits the confirmation code.
This performs the following functions:
1) Transmits the char to the ESB to change the throttle 2) Sends the new value the throttle should be changed to 3) Awaits for the appropriate return message 4) If the function was interrupted part way through by an interrupt, it is restarted
Parameters
void
Returns
void
Definition at line 68 of file Engine_funcs.c.
References ESBreceive, ESBtransmit, sendToESB(), throttle_per, and waitMS().
{
    ESBtransmit[0] = 't';
    ESBtransmit[1] = throttle_per;
    while (ESBreceive[0] != 'K'){
        sendToESB(2);
        waitMS(5);
    }
    ESBreceive[0] = 0; // clear out the first char so that it actually
       transmits
}
waitMS()
void waitMS (uint16_t msec)
Subroutine which will wait for a given number of milliseconds.
Parameters
in msec Number of milliseconds to wait
Returns
void
Definition at line 238 of file ECU_funcs.c.
References assign_bit(), and bit_is_clear.
{
    // This function utilizes timer 0 and a sequence of delay loops to delay for the desired time
    TCNT0 = 5;
    // begin the timer
    TCCR0B |= (1 << CS01) | (1 << CS00); // this will start the timer with a prescalar of 64
    for (uint16_t i = 0; i < msec; i++){
        while(bit_is_clear(TIFR0, TOV0));
        TIFR0 |= (1 << TOV0); // Clear the overflow flag by writing a 1 to it
    }
    assign_bit(&TCCR0B, CS01, 0);
    assign_bit(&TCCR0B, CS00, 0); // Turn off the timer
}